name: torchcrf
channels:
  - pytorch
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - filelock=3.12.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - jinja2=3.1.2
  - libcxx=16.0.3
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.41.2
  - libzlib=1.2.13
  - markupsafe=2.1.2
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - ncurses=6.3
  - networkx=3.1
  - openssl=3.1.0
  - pip=23.1.2
  - python=3.11.3
  - python_abi=3.11
  - pytorch=2.0.1
  - readline=8.2
  - setuptools=67.7.2
  - sympy=1.11.1
  - tk=8.6.12
  - typing_extensions=4.5.0
  - tzdata=2023c
  - wheel=0.40.0
  - xz=5.2.6
